---
# Install Zabbix agent
  - name: apt update
    apt:
      update_cache: yes

  - name: Download zabbix
    get_url:
      url: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-4+debian11_all.deb
      dest: "/tmp"

  - name: Install zabbix
    apt:
      deb: /tmp/zabbix-release_6.0-4+debian11_all.deb

  - name: apt update
    apt:
      update_cache: yes

  - name: install zabbix-agent
    apt:
      name:
        - zabbix-agent
# конфиг с прописанным ip сервера 
  - name: copy zabbix-apache-conf
    copy:
      src: zabbix_agentd.conf
      dest: /etc/zabbix/
  

  - name: Restart all sevices
    shell: |
      systemctl restart zabbix-agent
      systemctl enable zabbix-agent