---
- name: apt update
  apt:
    update_cache: yes

- name: copy filebeat.deb
  copy:
    src: filebeat-7.8.0-amd64.deb
    dest: ~/
# Могут возникнуть проблемы с deb файлом, например файл с оф.сайта elastic 
# Debian не захотел запускать поэтому рекомендую брать приложеный файл
- name: install filebeat
  apt:
    deb: ~/filebeat-7.8.0-amd64.deb
# конфиг с прописанными ip elastic
- name: copy filebeat.yml
  copy:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
  notify:
    - enable filebeat

- name: setup filebeat
  shell: 'filebeat setup'

- name: start filebeat
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: filebeat.service

- name: Return service state information as fact data
  service_facts:

- name: Show the status of filebeat service
  debug:
    var: ansible_facts.services['filebeat.service']['state']